### ISSUE TITLE
DE optimization with multivariate functions

### ISSUE THREAD

**Issue by Ellyuca** [mooscaliaproject/pymoode#5]
Hi.
Thanks for this amazing work.
I just discovered this package. In the tutorial notebook there are examples with univariate functions `f(x)`.

`def rastrigin(x):
    return np.sum(x * x - 10 * np.cos(2 * np.pi * x)) + 10 * np.size(x)
`
`functional_problem_1 = FunctionalProblem(n_var=2, objs=rastrigin,
                                         xl=np.full(2, -5.12), xu=np.full(2, 5.12),
                                         constr_ieq=[])`
Can you please explain why `n_var=2` when we have just one variable `x`?
Later edit: looking at the pymoo documentation, I found this: 
- `n_var` = Integer value representing the number of design variables
So, I am a bit confused.

Moreover, I was wondering if it is possible to use DE with multivariate functions:
- given, for example, a function `f(a,b,c,d,e,f)` with 5 variables, where each of the variables hasdifferent lower and upper limits (for example `a in [0,1], b in [0,2], c in [5,10], etc`).  The output of this function will be a single real value.  I want to find the best values for `a,b,c,d,f` that minimize the function `f`. How can I change the problem definition, the termination condition and the minimization process to fit this scenario?

Thank you for your time and help!
Have a great day!

**Comment by bruscalia** [comment]
Hi Ellyuca!

Thanks for your feedback!

All problems in pymoo (and pymoode) are assumed to be multivariate, and x is therefore assumed to be a numpy array. In the FunctionalProblem and ElementwiseProblem definitions, x is a 1d numpy array in which each element corresponds to one decision variable. Alternatively, on the Problem basic structure, x is assumed to be a two-dimensional array in which each column corresponds to one decision variable, whereas the lines correspond to different individuals. Notice there's no special distinction for scalar-variable problems. You can just create a problem with one variable (but stills considered a vector of 1 element).

In the definition of the problem you mentioned, x is assumed to be a 1d numpy array with two elements.

So, if you consider the FunctionalProblem of the example, you can read the previous example as:

`def rastrigin(x): return (x[0] * x[0] - 10 * np.cos(2 * np.pi * x[0])) + (x[1] * x[1] - 10 * np.cos(2 * np.pi * x[1])) + 10 * 2`

So, in answer to the second question, you can surely apply DE to multivariate functions. In your case, just by restructuring the function definition:

```
def fun(x):
    a = x[0]
    b = x[1]
    c = x[2]
    d = x[3]
    e = x[4]

   return do_your_operations(a, b, c, d, e, f)
```

Feel free to reach out to me in case you still have any doubts.

Just a quick tip: I found some problems on the 0.2.0 release because of changes in pymoo from 0.5.0 to 0.6.0. Please update your pymoode version to 0.2.3 to fix problems on exponential crossover if you want to try it. (I strongly prefer binomial crossover though).

Have a nice day too!

**Comment by Ellyuca** [comment]
Hi @bruscalia.

Thanks very much for the quick reply.
Oh, I see. This helps me out so much!

I have one quick question: can you pass to the function a parameter that is needed to compute final score, but doesn't need to be optimized? For example: 

````
def fun(x, M): 
      a = x[0]     
      b = x[1]
      c = x[2]
      d = x[3]
      e = x[4]    
      M_new = use_a_b_c_d_e_f_to_change_M
      score = compute_difference(M_new - M)    
      return score
````


where M is a matrix, and `a,b,c,d,e,f` are used to change the matrix.
So basically, I am trying to find the best `a,b,c,d,e,f` that will minimize the difference between the original matrix, and the new matrix. But I will like to be able to pass the matrix through the `func` definition.

I tried to modify the function as `funct(x,M)` and then also change the code in the ElementWiseProblem:
` def _evaluate(self, x, M, out, *args, **kwargs):
        out["F"] = func(x, M)`
but then, when I tried to run the code I get the following error:
`TypeError: _evaluate() missing 1 required positional argument: 'out'`

Any ideas on how to fix this?
Thanks once again for your help!

**Comment by bruscalia** [comment]
Hi @Ellyuca!

I'm not sure if there's an easy way to do so in pymoo, similar for instance to passing the args=() in scipy.optimize.minimize...

If you declare M before your function in your code it should probably work. Then, state the function with x as the only argument.

Also, if you are familiar with OOP, you can create your problem class including the M value. For instance:

```
from pymoo.core.problem import ElementwiseProblem
from pymoo.optimize import minimize
from pymoode.algorithms import DE

class MyProblem(ElementwiseProblem):

    def __init__(self, M):
        self.M = M
        super().__init__(n_var=..., xl=..., xu=...,)

    def _evaluate(self, x, out, *args, **kwargs):
        out["F"] = your_function(x, self.M)

res = minimize(MyProblem(YOUR_VAL_M), DE(), ("n_gen", 100))
```

Please let me know if it works for you.

Kind regards

**Comment by Ellyuca** [comment]
Hi @bruscalia,

I also ended up thinking about using the OOP solution. It does seem to be working for now. 
Tomorrow I will run some more tests, just to make sure that everything works.

I greatly appreciate your help.
Best wishes.

**Comment by bruscalia** [comment]
Hi @Ellyuca,

I hope everything goes well with your next tests tomorrow. I'll close this issue for now, but feel free to reach out to me here or at bruscalia12@gmail.com in case you have any further questions.

Kind regards,

**Comment by Ellyuca** [comment]
Hi @bruscalia.

First of all just wanted to say thanks once again. You suggestions were really helpful.
I am trying to extend the above mentioned problem to a multi-objective scenario. For example, given 2 conflicting objectives F1 and F2:
```
def F1_fun(x, M): 
      a = x[0]     
      b = x[1]
      c = x[2]
      d = x[3]
      e = x[4]    
      M_new = use_a_b_c_d_e_f_to_change_M
      score_1 = compute_difference(M_new - M)    
      return score_1


def F2_fun(x, M): 
      a = x[0]     
      b = x[1]
      c = x[2]
      d = x[3]
      e = x[4]    
      M_new = use_a_b_c_d_e_f_to_change_M
      score_2 = computer_another_metric(M_new, M)    
      return score_2
```

Is is possible to find the values of x that gives the best trade-off between F1 and F2?
I look at the example from your blog and I was thinking of doing something like:

```
class MyProblemTwoObj(ElementwiseProblem):

    def __init__(self, M):
        self.M = M
        super().__init__(n_var=..., xl=..., xu=...,)

    def _evaluate(self, x, out, *args, **kwargs):
        out["F"] = np.column_stack([F1_fun(x, self.M), F2_fun(x, self.M)])    


termination_multi = DefaultMultiObjectiveTermination(
    xtol=1e-8,
    cvtol=1e-8,
    ftol=1e-8,
    period=50,
    n_max_gen=NGEN,
)


res = minimize(MyProblemTwoObj(YOUR_VAL_M), nsga2, termination_multi)
```

In your examples for the multi-objective optimization you also have 
```
out["G"] = np.column_stack([G1, G2]) #with G1 and G2 defined in some way
```

I didn't understand the purpose of G. Could you please explain why you define it? It is mandatory to be used?

I am grateful for your help.
Thank you for your time and patience.
Best regards.

**Comment by bruscalia** [comment]
Hi @Ellyuca !

I'm glad I could help somehow :)

If you create a multi-objective problem, the algorithms should return a Pareto front of nondominated solutions, of which the best trade-off can be defined for each unique context.

You can find some multi-criteria decision-making strategies in this link: https://pymoo.org/mcdm/index.html, although each context is unique.

I present a brief introduction to MOO in this Medium article which can be helpful too: https://towardsdatascience.com/pymoode-differential-evolution-in-python-78e4221e5cbe

Now regarding G:

You can parse any attribute to the individuals of your population by adding pairs of (key, value) to the "out" dictionary. The most usual values you should include are:

- F the objective function(s)
- G the inequality constraint(s) (assumed to be negative when feasible)
- H the equality constraint(s) (I strongly advise you to try and eliminate degrees of freedom of your problem in a different manner if possible)

I suggest you take a look at these pymoo instructions: https://pymoo.org/constraints/index.html

Regarding the algorithm, I would suggest you use GDE3 with survival  = RankAndCrowding(crowding_func="pcd") in case of a 2-objective problem and either GDE3MNN or NSDER in case of problems with more than two objectives.

You can also try pymoo's native algorithms. NSGA-II, SPEA2, SMSEMOA are some suggestions.

Thanks for using pymoode!

My kindest regards,

Bruno Scalia
