### ISSUE TITLE
cannot import calc_crowding_distance

### ISSUE THREAD

**Issue by bakachan19** [mooscaliaproject/pymoode#6]
Hi.
Thanks for this great library.
I tried to run the multi-objective demo and I've encoutered this error:
```cannot import "calc_crowding_distance" from "pymoo.algorithms.moo.nsga2" ```

I've installed pymoode using the instructions: pip install pymoode. I have ```pymoode==0.2.6``` and ```pymoo==0.6.1.1```.

Any ideas and tips on how to solve this issue?
Thank you for your time and help!

**Comment by bruscalia** [comment]
Thanks for pointing out this issue @bakachan19! Can you try it with pymoo==0.6.0? Recently pymoode RankAndCrowding was fully incorporated into pymoo and changed that import path.

**Comment by bruscalia** [comment]
@bakachan19 I just released a candidate version intended to be compatible with pymoo==0.6.1.1. Can you check if you can run it with pymoode==0.3.0.rc2 ?

**Comment by bakachan19** [comment]
Hi @bruscalia,
I apologize for the late reply. I was offline for holiday break.
I will try it and let you know.
Thank you!

**Comment by bakachan19** [comment]
Hi @bruscalia.
I installed pymoode==0.3.0.rc2 and I run the ZDT1 problem from the multi-objective tutorial. It runs.

For the previous version that I have installed (pymoode=0.2.6) I had to an import in order to make it run. In pymoode/survival/metrics.py I changed the import from this:
```from pymoo.algorithms.moo.nsga2 import calc_crowding_distance as _calc_crowding_distance```
to this:
```from pymoo.operators.survival.rankd_and_crowding.metrics import calc_crowding_distance as _calc_crowding_distance ```

Thanks!
Have a nice day.

**Comment by bruscalia** [comment]
@bakachan19 I'm sorry my response to your comment wasn't sent! I had closed this with a comment last week but there might have been some connection error and the message never left.

Thank you very much for your contribution and for testing the new release!
