### ISSUE TITLE
Integration into pymoo

### ISSUE THREAD

**Issue by ttusar** [mooscaliaproject/pymoode#7]
Thanks for providing this library! 

More a question/suggestion than an issue: Why is it separate from `pymoo`? Wouldn't it make sense to integrate the DE-based algorithms into `pymoo`?

**Comment by bruscalia** [comment]
Hi @ttusar! Sorry for the late reply, I'm traveling on vacation for a few weeks and a little off from github.

Thanks for the feedback! I've already included several operators into pymoo and opened a PR for others. However, Julian was working in a major refactoring and we postponed it indefinetely. But surely the goal is to later fully incorporate it into pymoo.
